---
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    cpus: 0.5
    mem_limit: 200m
    ports:
      - 80:80
      - 443:443
      - "443:443/udp"
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
      - CADDY_DOCKER_CADDYFILE_PATH=/config/Caddyfile
    env_file:
      - .env
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy-data:/data
      - caddy-certs:/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory
    restart: unless-stopped

  app:
    image: kenyawest/rss-proxy-transformer:latest
    container_name: rss-proxy-transformer
    cpus: 0.5
    mem_limit: 200m
    env_file:
      - .env
    networks:
      - caddy
    labels:
      caddy: "${DOMAIN}"
      caddy.handle_path: "/mycustompath/*"
      caddy.handle_path.0_rewrite: "* /feed"
      caddy.handle_path.1_reverse_proxy: "{{ upstreams 5000 }}"

networks:
  caddy:
    external: true